var ghpages = require('gh-pages');
var path = require('path');

ghpages.publish(path.join(__dirname, '.'),{
repo: 'https://solgarcr.github.io/demoReact.github.io'}, function(err) {
console.log(err);
console.log("Se ha subido a gh-pages correctamente");
});